site_name: cmenpy
site_url: https://ltsim.github.io/cmenpy
repo_url: https://github.com/ltsim/cmenpy

theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest

nav:
  - Home: index.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [cmenpy]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            members_order: source
            separate_signature: true